ignore:
  - "src/htr2hpc/settings.py"   # not executed in test environment by design
  - "src/htr2hpc/migrations/"   # standard Django migrations
  - "src/htr2hpc/tasks.py"      # Celery tasks requiring full HPC+eScriptorium stack

coverage:
  status:
    project:
      default: false
      all:
        target: 57%
        paths:
          - "src/"
      tests:
        target: 96%
        paths:
          - "tests/"
    patch:
      default:
        target: 95%
