# Generated by Django 4.2.17 on 2025-01-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_legacy_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, null=True, unique=True, verbose_name="email address"
            ),
        ),
    ]
