# Generated by Django 4.2.16 on 2025-01-28 16:13

from django.db import migrations, models


class OverrideAlterField(migrations.AlterField):
    # extend alterfield migration so we can override the app_label
    override_app_label = "users"

    def state_forwards(self, app_label, state):
        super().state_forwards(self.override_app_label, state)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        super().database_forwards(
            self.override_app_label, schema_editor, from_state, to_state
        )

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        self.database_forwards(
            self.override_app_label, schema_editor, from_state, to_state
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_legacy_mode"),
    ]

    operations = [
        OverrideAlterField(
            model_name="User",
            name="email",
            field=models.EmailField(
                max_length=255, null=True, unique=True, verbose_name="email address"
            ),
        ),
    ]
